name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Installe Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Installe les dependences
      run: npm ci

    - name: Build Angular project
      run: npm run build -- --configuration production

    - name: Debug build output
      run: ls -R dist/czizou

    - name: Clean remote target folder
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        script: sudo rm -rf /var/www/czizou.com/*

    - name: Deploy to VPS
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        source: dist/czizou/browser
        target: /var/www/czizou.com
        strip_components: 1
