name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build Angular project
      run: npm run build -- --configuration production

    - name: Show build output
      run: ls -R dist/czizou/browser

    - name: Clean remote folder
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        script: |
          sudo rm -rf /var/www/czizou.com/*
          sudo mkdir -p /var/www/czizou.com
          sudo chown -R $USER:$USER /var/www/czizou.com

    - name: Setup SSH key
      run: |
        echo "${{ secrets.VPS_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Deploy with manual SCP
      run: |
        scp -o StrictHostKeyChecking=no -r -i key.pem dist/czizou/browser/* ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/czizou.com/

    - name: Fix permissions
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        script: |
          sudo chown -R www-data:www-data /var/www/czizou.com
          sudo find /var/www/czizou.com -type d -exec chmod 755 {} \;
          sudo find /var/www/czizou.com -type f -exec chmod 644 {} \;
